FlutterKaigi/2024

.github/workflows/deploy-web.yaml
- [actions/deploy-pages](https://github.com/actions/deploy-pages)を利用する方法に変更します
- こちらの手法がGitHub Pages公式のDocsに掲載されていたため。
=> [Website] Production DeployのWorkflowを修正

apps/website/lib/ui/components/footer/site_footer.dart
- リンク先が Mediumのホームページになっていたので、FlutterkaigiアカウントのMediumページへ変更
=> [Website] Mediumのリンクを修正

.vscode/cspell.json, .vscode/settings.json, apps/app/lib/main.dart, apps/app/lib/widget/debug_screen.dart
- https://github.com/FlutterKaigi/2024/issues/47
- https://github.com/FlutterKaigi/2024/issues/48
ライセンスページをデバッグ画面で表示するようにしました
https://github.com/FlutterKaigi/2024/assets/162671982/1255df6f-51ad-4631-a422-eb09e728de7f
|-|-|-|
| | | |
=> 【App】ライセンスページを表示するようにしました。

apps/website/web/index.css, apps/website/web/index.html, apps/website/web/index.js
- Closes #121
FlutterがロードされるまでのローディングUIを追加しました
https://github.com/FlutterKaigi/2024/assets/41745521/ee75ee18-4f35-46ec-a912-24fcf69a3589
[Material Web](https://github.com/material-components/material-web)を利用しています．
追加のビルドをしない方法で解決できたのでビルドフローは変更していません．
FlutterKaigi 2024のカラーを指定しています．
Material WebのローディングUIに対してグラデーションを指定できそうになかったので4色の切り替える設定を適用しています．
=> [website] ローディングUI追加

.vscode/tasks.json
なし
tasks.json を作成して supabase 関連のよく使うコマンドを設定しました。
VS Code 上でコマンドを実行している様子です。
https://github.com/user-attachments/assets/f506f536-63f8-4e25-91c9-da84e5399aa6
https://github.com/user-attachments/assets/fde25577-5efe-4c6b-accb-9f62a60436e3
- https://code.visualstudio.com/docs/editor/tasks
- https://supabase.com/docs/reference/cli
=> chore: tasks.json を作成して supabase 関連のよく使うコマンドを設定

apps/website/build.yaml, apps/website/slang.yaml
- slangの設定を記述するファイルを変更しました 
- `slang.yaml`から`build.yaml`に設定記述場所を変更しました
=> [Website] slang.yamlからbuild.yamlに設定ファイルを変更

packages/app/features/about/assets/l10n/app_en.arb, packages/app/features/about/assets/l10n/app_ja.arb, packages/app/features/about/lib/src/gen/l10n/l10n.dart, packages/app/features/about/lib/src/gen/l10n/l10n_en.dart, packages/app/features/about/lib/src/gen/l10n/l10n_ja.dart, packages/app/features/about/lib/src/ui/about_page.dart
- Closes #44 
- プライバシーポリシー ページ（外部サイト）への遷移する機能を作成しました。
| 日本語 | 英語 | Design |
|-|-|-|
| <video src="https://github.com/user-attachments/assets/77ac2977-4d58-483e-a2e4-abb117e67d3b" width="300" />  | <video src="https://github.com/user-attachments/assets/45a15214-4113-4dfb-8a3f-7e5cee5b0827" width="300" /> | <img src="https://github.com/user-attachments/assets/b4ad5ad8-f89d-452a-a4e6-438e7cd862d4" width="300" /> |
- 特になし
=> [App] プライバシーポリシー(外部サイト)へ遷移する

apps/app/analysis_options.yaml, apps/website/analysis_options.yaml
- apps/* の`analysis_options.yaml`が配置されておらず、Linterが無効だったため セットしました。
=> fix: analysis_options.yamlをapps/*にも追加

apps/app/lib/main.dart, packages/app/cores/core/lib/src/providers/shared_preferences_instance.dart, packages/app/cores/core/lib/src/providers/shared_preferences_instance.g.dart, packages/app/cores/designsystem/lib/src/font_family.dart, packages/app/cores/designsystem/lib/src/font_family.g.dart
- Closes none
https://github.com/FlutterKaigi/2024/pull/199#discussion_r1739606450
上記コメントを見ました。SharedPreferencesに同期的にアクセスできるのは(結構)便利なため、Providerの実装を整理し、同期的にアクセスできるようにしています。
`late`によるunwrapとなるため、main functionにてinitを実行しないとruntime exceptionとなります。ただ、これぐらいなら許容できるのではないか、と考えています。
|-|-|-|
| | | |
=> feat: Add sync shared_preferences provider

packages/common/data/supabase/migrations/20240904185013_add_stripe_wrapper.sql, packages/common/data/supabase/tests/stripe/rls_test_as_anon.sql, packages/common/data/supabase/tests/stripe/rls_test_as_authenticated.sql, packages/common/data/supabase/tests/stripe/stripe_basic_test.sql
- Stripe Data Connectのセットアップをしました
- `stripe.checkout_sessions`テーブルを作成しました
- cf. https://supabase.com/docs/guides/database/extensions/wrappers/stripe#checkout-sessions 
- `stripe schema`に作成されているため、Service Role以外ではアクセスできません
- Unit Testで確認しています
=> [data, ticket] stripe data connectのセットアップ

packages/common/data/lib/session.dart, packages/common/data/lib/src/model/profile_social_networking_service.dart, packages/common/data/lib/src/model/profile_social_networking_service.freezed.dart, packages/common/data/lib/src/model/profile_social_networking_service.g.dart, packages/common/data/lib/src/model/session.dart, packages/common/data/lib/src/model/session.freezed.dart, packages/common/data/lib/src/model/session.g.dart, packages/common/data/lib/src/model/session_speaker.dart, packages/common/data/lib/src/model/session_speaker.freezed.dart, packages/common/data/lib/src/model/session_speaker.g.dart, packages/common/data/lib/src/model/session_venue.dart, packages/common/data/lib/src/model/session_venue.freezed.dart, packages/common/data/lib/src/model/session_venue.g.dart, packages/common/data/lib/src/model/sns.dart, packages/common/data/lib/src/model/sns.freezed.dart, packages/common/data/lib/src/model/sns.g.dart, packages/common/data/lib/src/model/view/profile_with_sns.dart, packages/common/data/lib/src/model/view/profile_with_sns.freezed.dart, packages/common/data/lib/src/model/view/profile_with_sns.g.dart, packages/common/data/lib/src/model/view/session_venues_with_sessions.dart, packages/common/data/lib/src/model/view/session_venues_with_sessions.freezed.dart, packages/common/data/lib/src/model/view/session_venues_with_sessions.g.dart, packages/common/data/lib/src/repository/session_repository.dart, packages/common/data/lib/src/repository/session_repository.g.dart, packages/common/data/lib/src/repository/staff_repository.dart, packages/common/data/supabase/migrations/20240921100801_add_session_table.sql, packages/common/data/supabase/util/add_sample_sessions.sql
> [!WARNING]
> - #235 をマージしてから本PRをマージしてください
- 各種テーブル・VIEWに対するRepositoryを作成しました
- `SessionRepository`: `public.sessions`テーブルに対するCRUD処理・`public.session_venues_with_sessions` Viewに対するSELECT処理を管理
- `SessionVenueRepository`: `public.session_venue`テーブルに対するCRUD処理
- `SessionSpeakerRepository`: `public.session_speaker`テーブルに対するCRUD処理
- SELECT処理だけではなく、Create, Update, Delete処理も実装しているのは `admin`権限をもつユーザ(=FlutterKaigiの一部メンバー)がそういった処理をできるようにするためです
- UIを実装できるかどうかわかりませんが一応作成しておきました
- 一般ユーザはRLSに弾かれます
=> [data] セッション関連のRepositoryを作成

api/package.json, api/pnpm-lock.yaml, api/src/bindings.d.ts, api/src/index.ts, api/src/middleware/rateLimiter.ts, api/src/routes/v1/v1.ts, api/wrangler.toml
> [!WARNING]
> - 以下PRをマージしてから本PRをマージしてください
>   - #235 
>   - #237 
>   - #240
>   - #241
>   - #242 
>   - #243 
>   - #245
>   - #246 
>   - #247 
>   - #250 
>   - #252 
>   - #253 
>   - #255
> - PRの宛先を`main`ブランチに変更すること 
- プロモーションコード周りのエンドポイントを作成しました
- **`PUT /v1/promotion`**: JSON Bodyの`metadata`, `maxRedemptions`に従った100%のプロモーションコードを発行します (要ログイン・`role() = admin`を要求)  
- **`GET /v1/promotion`**: クエリパラメータ`code`にマッチするプロモーションコードがあるかどうかを検証します
- ある場合は、metadataを返します
- ない場合は、404 Not Foundになります
- 本エンドポイントは、ランダムな値で検証を行い プロモーションコードを探そうとする行為を防ぐため レート制限の対象にしています
- 1分間に10回まで叩けます
- `PUT /v1/promotion`によって生成されるプロモーションコードは 2文字+6文字で成り立っていて 2文字部分は4種類・6文字部分は[0-9, a-f]の`16^6`の複雑性。
- $4 \times 16^6 =　6,7108,864$　より、1分に10回試行すると 4660日で全探索できる計算になる。
- 多分十分。。。
- (`PUT …
=> [ticket] (api) プロモーションコード周りのAPIを作成

api/package.json, api/pnpm-lock.yaml, api/wrangler.toml
- 本日の[Cloudflare Builder Day 2024](https://blog.cloudflare.com/builder-day-2024-announcements/#logs-for-every-worker)で、Cloudflare Workersの永続ログのOpen Beta版がリリースされました
- Cloudflare Workersが吐くログをダッシュボードから見れるようにしてくれる機能です
- エラー率やレイテンシを観測できるため導入したいです
- 2024.11.1 より課金が始まります
- Workers Free(こちらに該当します): 1日20万ログまで、3日間保持
- Workers Paid(将来的にこちらへ移行する可能性もあります): 月間2,000万ログまで無料 + $0.60/100万ログ、7日間保持
- 現在、Workers Freeなので お金がかかる心配はない
=> [ticket] (api, chore): Workers Logを有効化・各種依存関係の更新

apps/app/pubspec.lock, apps/ticket_web/pubspec.lock, apps/ticket_web/pubspec.yaml, apps/website/pubspec.lock, apps/website/pubspec.yaml, packages/app/features/news/pubspec.yaml, packages/common/data/pubspec.lock, packages/common/data/pubspec.yaml, pubspec.lock
- Dart 3.5以降かつdart2wasmを用いた場合に、`Supabase.initialize()`が正常に動いていなかった
- 根本原因は　https://github.com/supabase/supabase-flutter/issues/1047
- 上記と同じ理由で、`vector_graphics`も正常動作していなかったので 修正版にoverrideしています
- この問題を修正するPR https://github.com/supabase/supabase-flutter/pull/1048 のバージョンを利用するようにしました
- 修正がマージされ、新しいバージョンがリリースされたら そちらを利用するように戻します
=> [website] yet_another_json_isolate, vector_graphicsを修正版にoverride

.github/workflows/check-pr.yaml, .github/workflows/wc-check-changes.yaml, .github/workflows/wc-check-diff.yaml
- Closes #274
`melos run rebuild` コマンドを実行して Git の差分を確認するという生成ファイルの最新チェック用のワークフローを作成しました。
見た目への影響はないため省略します。
近いうちに build_runner のキャッシュについてのワークフローを組み込む予定です。
=> ci: 生成ファイルの最新チェック用のワークフローを作成

apps/ticket_web/lib/core/util/full_screen_loading.dart, apps/ticket_web/lib/feature/profile/data/profile_notifier.dart, apps/ticket_web/lib/feature/profile/data/profile_notifier.g.dart, apps/ticket_web/lib/feature/ticket/ui/components/profile_avatar_choice_dialog.dart
- チケット画面のバグを修正
- `FullscreenLoadingScreen.showUntil()`関数
- Android端末でCircularProgressIndicatorが全画面に広がって表示されてしまう問題を修正
- 任意の領域をタップすることで、全画面読み込みブロッキングを解除できる問題を修正
- プロフィール画像を選択する`ProfileAvatarChoiceDialog`が重なって表示される問題を修正
- https://flutterkaigi.slack.com/archives/C07DX137CNB/p1728152617043339?thread_ts=1728112509.609509&cid=C07DX137CNB
=> [ticket] チケット画面の軽微なバグを修正

api/package.json, api/pnpm-lock.yaml
なし
セキュリティの警告が出ていたため対応しました。
https://github.com/FlutterKaigi/2024/security/dependabot/1
`youch` が `cookie ^0.5.0` に依存していることで `pnpm update` コマンドでは更新できなかったため、強制的に上書く設定を追加して `pnpm install` で更新しました。
軽く動作確認できたらマージしてみて、セキュリティの警告が消えて無事に動作したか確認できれば、、！
特になし
- https://pnpm.io/ja/cli/update
- https://pnpm.io/ja/package_json#pnpmoverrides
=> [api] fix: cookie を 0.7.1 以上で上書き

apps/ticket_web/lib/core/provider/image_picker/image_picker_for_io.dart, apps/ticket_web/lib/core/provider/image_picker/image_picker_for_io.g.dart, apps/ticket_web/lib/core/provider/image_picker/image_picker_for_web.dart, apps/ticket_web/lib/core/provider/image_picker/image_picker_for_web.g.dart, apps/ticket_web/lib/core/provider/image_picker_provider.dart, apps/ticket_web/lib/feature/profile/data/profile_notifier.dart, apps/ticket_web/pubspec.lock, apps/ticket_web/pubspec.yaml
- `image_picker_for_web` Packageに依存していたため、macOSのビルドが成功していなかった
- プラットフォームごとにファイルを分割して、macOSでもビルド/動作できるようにしました
=> [ticket] macOSでビルドできない問題を修正

api/src/routes/v1/v1.ts
個人スポンサーにはプロモーションコードは存在しないため、先に分岐をする必要がある
- https://flutterkaigi.slack.com/archives/C07DX137CNB/p1728190903245129?thread_ts=1728102935.423529&cid=C07DX137CNB
=> [ticket] 個人スポンサーチケットの検証フローを修正

.github/workflows/update-application-cache.yaml, .github/workflows/wc-check-diff.yaml
なし
- 以前 `**/.dart_tool/build/generated` ディレクトリ配下のみをキャッシュするようにしていたが、これだけだと容量が小さかったためか `melos run rebuild` の高速化には繋がらなかった。
- YUMEMI のプロジェクトでは `**/.dart_tool/build` ディレクトリ配下にしているが、現状問題発生しておらず高速化できている。
- https://github.com/yumemi-inc/flutter-mobile-project-template/blob/6b68c4fdd5f631faab0d7b8d220987fe802cb5eb/.github/workflows/wc-check-diff.yaml#L27
なし
=> [all] ci: build_runner のキャッシュについて build ディレクトリごとキャッシュするように変更

.github/workflows/wc-check-packages.yaml
- Closes #350 
CI のパッケージチェック時に循環依存があったらエラーになるようにしました。
https://melos.invertase.dev/commands/list#--cycles
挙動は↓で確認済み
https://github.com/FlutterKaigi/2024/pull/356
なし
=> [all] ci: パッケージのチェックワークフローに循環依存チェックを追加

api/src/features/cron/scheduled.ts
- Slackのチケット枚数状況通知タスクの修正です
- チケット枚数が不明なチケット種別 のチケットに対する分岐を追加しました
- https://flutterkaigi.slack.com/archives/C07R914V1FU/p1729173321916769 修正後の投稿
- エラー
=> fix: 最大枚数が不明なチケット種別ががある時の例外処理

.github/ISSUE_TEMPLATE/task_for_contributor.yaml, .github/ISSUE_TEMPLATE/task_for_staff.yaml, .github/labeler-issue.yaml, .github/workflows/labeler-issue.yaml, .vscode/cspell.json
なし
**※ #364 がマージされてからマージします。**
- 外部コントリビューター用に Issue テンプレートを作成しました。
- FlutterKaigi スタッフ用の Issue テンプレートはすでにありますが、新たに作成しています。既存の Issue テンプレートはもう少し落ち着いてから削除予定です。
なし
- https://github.com/stefanbuck/github-issue-parser
- https://github.com/redhat-plumbers-in-action/advanced-issue-labeler
- https://docs.github.com/ja/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow
=> [All] ci: Issue テンプレートと Issue 作成時にラベル付与するワークフローを作成

.github/workflows/deploy-supabase.yaml, .github/workflows/replace-contributors.yaml
なし
- コントリビューター一覧の取得方法を `const contributors = response.data;` のように修正
- コントリビューター一覧の取得結果を次のステップに渡すときに `JSON.stringify()` を利用
- コントリビューター一覧を通常ユーザーのみにフィルタリング（botユーザーを排除）
- `replace_contributors` のみ JWT での認証チェックをしないように修正
- こうしないと認証チェックがデプロイのたびに必須になる
無事にデータを入れることできました 🎉
=> fix: コントリビューター一覧の取得方法を修正

api/src/index.ts
- チケットシステムAPIのCORSに`flutterkaigi.jp`ドメインを追加します
- チケットシステムを`flutterkaigi.jp`のサブドメインに移行する準備です
=> [ticket-api] `flutterkaigi.jp`ドメインをCORSの`Access-Control-Allow-Origin`に追加

.github/ISSUE_TEMPLATE/task_for_contributor.yaml, .github/ISSUE_TEMPLATE/task_for_staff.yaml, .github/labeler-issue.yaml
なし
現状の Issue テンプレートだとすべてに関連するもの（ `.DS_Store` がコミットされている件など ）を作成することができなかった。
=> [All] chore: すべてに関係する Issue を作成できるように改善

packages/common/data/lib/src/repository/contributor_repository.dart
- Closes https://github.com/FlutterKaigi/2024/issues/397
- コントリビューターについて、コントリビューション数の降順で取得するように対応しました
-  対応後のコントリビューター一覧
- ログ出力で確認
- 特にありません
=> fetch contributions in descending order

packages/app/features/about/lib/src/ui/contributors/contributors_page.dart, packages/app/features/about/lib/src/ui/sponsors/sponsors_page.dart, packages/app/features/about/lib/src/ui/staff/staff_page.dart
- Closes #385
- Closes #391 
- Closes #392
- 「スタッフ一覧」「スポンサー一覧」「コントリビューター一覧画面」にて、特にiOSにて最下部までスクロールした時に項目が欠けていたため、`SafeArea`を追加しました
| Before | After | 
|-|-|
|<img src=https://github.com/user-attachments/assets/10968fd3-7011-4d82-bb0a-538f1df554cc  width=100%> |<img src=https://github.com/user-attachments/assets/fcdfa121-06a3-40fe-ade8-279fe43881e1  width=100%> | 
| Before | After | 
|-|-|
|<img src=https://github.com/user-attachments/assets/83bab688-e152-45dc-ac9e-ebc711676dd3  width=100%> | <img src=https://github.com/user-attachments/assets/aa78c73a-6329-4203-9e4a-9e09ff3ed493  width=100%>| 
| Before | After | 
|-|-|
|<img src=https://github.com/user-attachments/assets/250f57b4-ba2c-4d44-b167-e66f023d137e  width=100%> | <img src=https://github.com/user-attachments/assets/4513aa23-d55a-45d …
=> add SafeArea to Staffs, Contributors and Sponsors page

apps/app/android/app/build.gradle, apps/app/defines/development.env, apps/app/lib/main.dart, apps/app/pubspec.lock, melos.yaml, packages/app/cores/core/lib/providers.dart, packages/app/cores/core/lib/src/providers/package_info_instance.dart, packages/app/cores/core/lib/src/providers/package_info_instance.g.dart, packages/app/cores/core/pubspec.lock, packages/app/cores/core/pubspec.yaml, packages/app/cores/designsystem/pubspec.lock, packages/app/cores/settings/pubspec.lock, packages/app/features/about/lib/src/ui/about_page.dart, packages/app/features/about/pubspec.lock, packages/app/features/news/pubspec.lock, packages/app/features/session/pubspec.lock, packages/app/features/venue/pubspec.lock
#413 
- 開発環境用のパッケージ名のサフィックスに `.dev` を追加
- ライセンスページにバージョンとパッケージ名、アプリのライセンス表記を表示
| 開発環境 | 本番環境 |
|-|-|
| <img src=https://github.com/user-attachments/assets/ffa6ac50-4c5a-4c5f-bba0-4c30a03adf09 width=320 /> | <img src=https://github.com/user-attachments/assets/9fc4f282-6f23-4acc-8136-790afbfad8a7 width=320 /> |
=> [App] feat: パッケージ名を環境ごとに設定

.github/workflows/deploy-app-android.yaml, .vscode/cspell.json, apps/app/android/app/build.gradle, apps/app/android/fastlane/Fastfile, apps/app/android/gradle/wrapper/gradle-wrapper.properties, apps/app/android/settings.gradle, melos.yaml
#413 
- Android アプリのビルド設定を Gradle, Melos に追加
- 最新の　Android Studio に対応するために Gradle のバージョンを更新
- 仮のデプロイワークフローファイルを作成
- apps/app/android/fastlane/Fastfile を仮作成
ちゃんと手元でビルドできることは確認済み。別でワークフロー作成のプルリクエスト提出予定です。
https://github.com/user-attachments/assets/a3840006-d6e3-4a08-b4e0-c9877526a195
- Android Gradle プラグインの 8.3 系の最新は 8.3.2
- https://developer.android.com/build/releases/past-releases/agp-8-3-0-release-notes?hl=ja#patch-releases
- Gradle は 8.4 に上げなければならない
- https://developer.android.com/build/releases/past-releases/agp-8-3-0-release-notes?hl=ja#compatibility
=> [App] chore: アプリの appbundle のビルド設定を追加

packages/app/features/about/lib/src/ui/staff/staff_list_item.dart
- Closes #396
スタッフメンバー一覧でスタッフをタップした際、その人のGitHubページに遷移するようにしました。
https://github.com/user-attachments/assets/bccaa5a8-3d56-447a-8dbe-ca639c2dd734
=> [App] スタッフメンバー一覧のタップイベントを追加

apps/app/android/app/build.gradle
- Closes #444 
`key.properties` ファイルが存在しないときにも設定値を読み込むようになっており、一部のメンバーのみしかビルドができない状態になっていたため、ファイルの存在チェックをするようにしました。
`key.properties` ファイルを削除しても無事にビルドができ、アプリが起動するところまで確認できました。
=> [App] fix: key.properties ファイルが存在するときのみ記載するように修正

apps/website/web/index.html
- `2024.flutterkaigi.jp`に変更した際に、Faviconの変更が抜けていたのでこちらで対応します
=> [website] Faviconが表示されていない問題の修正

packages/app/features/session/lib/src/ui/session_page.dart
- Closes #480 
- TextPainter を使用して、動的にサイズを取るようにしました。
- TextPainter 使用時に TextDirection が intl と競合したため、import に as intl として競合解決しました。
|-|-|-|
|<img src="https://github.com/user-attachments/assets/861da199-994f-4f0b-afb8-c83edb5b564c" width="300" /> | <img src="https://github.com/user-attachments/assets/938267f2-8e71-4c69-9e3b-360a20dc012b" width="300" />| |
|<img src="https://github.com/user-attachments/assets/850ab72a-c244-4a68-a566-94d864a9d77c" width="300" /> | <img src="https://github.com/user-attachments/assets/098046c4-a5a1-456a-beb8-9ee31c13455f" width="300" />| |
- TextSpan での textStyle ですが、SliverAppBar.large と SliverAppBar.medium でのデフォルトがこれだろうと半ば強引に決めうちでやっています。
-  お作法的な問題がなく、better であればマージしていただき、より良いものがあれば、別途ご対応お願いいたします。
=> fix: セッション詳細画面でのタイトルの見切れを修正

packages/app/features/news/lib/src/ui/news_page.dart
- Closes #381
お知らせ一覧画面で有効なお知らせのみを表示するようにしました。
有効かどうかの条件は、Issue #381 に書かれているとおりです。
> 有効であるためには、以下の2つの条件を満たしている必要があります:
> 
> * ニュースがすでに始まっている（開始時刻が現在より前）。
> * ニュースがまだ終了していない（終了時刻が現在より後、もしくは終了時刻が指定されていない）。
お知らせは `NewsRepository.getNews()` → `newsProvider` という経路でDB上のすべてのお知らせが返ってくるようでしたので、`NewsPage` の方でフィルタリングするようにしました。
できればもっと上流のところ（DBへのクエリなど）でフィルタリングしたいところですが、それらは common 配下にあり他にも影響しそうでしたので、一旦局所的な対応までとしております。
見た目の変更はないですが、意図したとおり絞り込まれた結果の画面を添付します。
次のようなお知らせのリストを `newsProvider` から返すようにして確認しました。
```dart
[
News(
id: 1,
text: '掲載終了しているお知らせ',
url: Uri.parse('https://example.com'),
startedAt: DateTime(2024, 4),
endedAt: DateTime(2024, 10),
),
News(
id: 2,
text: '掲載中のお知らせ（終了日あり）',
url: Uri.parse('https://example.com'),
startedAt: DateTime(2024, 10),
endedAt: DateTime(2024, 12),
),
News(
id: 3,
text: …
```
=> [app] お知らせ一覧画面：有効なお知らせのみを表示する

packages/app/cores/core/lib/src/constants/official_social_urls.dart, packages/app/features/about/lib/src/ui/about_page.dart
- Closes #415
- About画面のGitHubアイコンのタップでリポジトリを開く
- Githubアプリインストール時はアプリで開き、未インストールの場合はWebブラウザで開きます。
|- | ブラウザで開く場合 | アプリで開く場合 |
|-|-|-|
| | <video src="https://github.com/user-attachments/assets/0c9c6b32-340d-4039-a3ea-8db64e119bbc" width="300" > | <video src="https://github.com/user-attachments/assets/8b38f5a4-ec99-4c32-a772-3e76db80dd60" width="300" > |
よろしくお願いします！
=> [app] About画面のGitHubアイコンのタップでリポジトリを開く

packages/common/data/supabase/migrations/20241110162100_add_semver_components.sql, packages/common/data/supabase/migrations/20241110163100_add_app_version_table.sql, packages/common/data/supabase/tests/app_minimum_versions_test.sql, packages/common/data/supabase/tests/semver_components_test.sql
#459 
アプリの強制バージョンアップ機能のために、雑にアプリの最低バージョンを保持しておくテーブルを作成してみました。
- １つのレコードだけで運用していこうかなとも思ったのですが、運用記録が残るように複数レコード前提として設計してみました。
- 基本的に Android, iOS で同じバージョンになると思ったのですが、異なるバージョンの可能性もあるのでレコード分けてより安全に運用できるようにしてみました。
アプリでの実装は別のプルリクエストに分けて提出するので、詳しい仕様のすり合わせはそこでレビューいただければと思います。
意図通りに動作していそうです。
=> [Data] feat: アプリの最小バージョンを管理するテーブルを作成

apis/supabase-types/src/types/index.ts, apis/website-html-rewriter/src/ogImage.tsx, apis/website-html-rewriter/src/server.ts
> [!NOTE]
> - #496 をマージしてください
- SpecialSponsorのOG生成に対応しました
- 具体的には、Cloudflare Workersがスポンサー情報を取ってくる時に`sponsor`テーブルではなく `sponsor_v2`ビューを使うようにしました
| DroidKaigi | Pocketalk|
| - | - |
|![image](https://github.com/user-attachments/assets/cd30e8a6-0bf8-4849-b0ff-9ddfa1308f39)|![image](https://github.com/user-attachments/assets/09040be3-88e4-40ca-894e-8eef613e7e0a)|
https://flutterkaigi.slack.com/archives/C06T5TXN19R/p1731348837612229?thread_ts=1731342321.703459&cid=C06T5TXN19R
=> [website_api]: SpecialSponsorのOGP生成に対応

.vscode/settings.json
- Closes #409
melos.yamlのSchemaチェックの追加、および動作確認を行いました。
以下のように、YAML拡張を追加したVSCodeを使用していると、schemeに沿わない書き方の場合にエラーが出ます
(ただの感想ですが) runとexecが両方書いてあった場合もエラー出してほしいなと思いました..
=> [All] melos.yaml の公式スキーマを参照する

packages/common/data/supabase/migrations/20241112193700_alter_profiles_with_sns_for_individual_sponsor.sql
- 個人スポンサーの一覧を返す`profiles_with_sns_for_individual_sponsor`viewですが、`profiles_with_sns`viewとレスポンスの型が異なっていたので `profiles_with_sns_for_individual_sponsor`側を統一しました
- Dart側の型定義は既に統一されていました(`ProfileWithSns class`で表現されています)
=> [data] 個人スポンサーのプロフィールを返すViewのバグ修正

apps/ticket_web/defines/production.env, apps/ticket_web/defines/staging.env.example
- 環境変数に格納している TicketAPIのBaseURLの末尾にスラッシュがついており、「ウォレットに追加」の遷移でNotFoundになっていた
- 今までAPIを叩く時は Dioを用いていたため 正規化されており気が付かなかった
=> [ticket_web](fix): 環境変数のBaseURLでは 末尾のスラッシュを削除

packages/app/features/session/lib/src/data/model/session_date.dart, packages/app/features/session/lib/src/ui/sessions_page.dart
- Closes #491 
- セッション一覧画面でのDay1とDay2の`ScrollController`や`Widget`が同等のものを利用していたため、Widget自体は同等のものを利用する様にし、`ScrollController` / `PageStorageKey`を独立したものを利用する様にし、スクロールを独立させました。
| Before | After |
|-|-|
|　<video src="https://github.com/user-attachments/assets/69791a38-affb-492e-9546-6261e14aab23" width="300" > | <video src="https://github.com/user-attachments/assets/039e4a4d-c052-4508-9a2d-ba1ef6bb2fce" width="300" > |
[参考](https://api.flutter.dev/flutter/widgets/PageStorage-class.html)
=> #491 [app] Day 1 と Day 2 のスクロール位置が同期されてしまっている

packages/app/cores/designsystem/lib/src/ui/main_logo.dart
- Closes #383 
`MainLogo` の画像に `excludeFromSemantics` を追加
|-|-|-|
| <img src="https://github.com/user-attachments/assets/684bbb2c-e01f-417b-9fce-6b198e44ee62" width="300" /> | <img src="https://github.com/user-attachments/assets/2079fa48-cfba-4b78-8a45-39a80400527a" width="300" /> | |
=> [App] 左上に表示されるMainLogoにexcludeFromSemanticsパラメータを追加する

packages/app/features/about/lib/src/ui/about_page.dart
- Closes #482 
- XとGithubのエフェクトが反映される範囲が小さかったため、Paddingを使用し、領域を広げてみました。
- Paddingを使用した分、SizedBoxの余白を削除することで、位置などについてはできるだけ変わらないようにしました。
| Before | After | Design | Design |
|-|-|-|-|
| <img src="https://github.com/user-attachments/assets/c1f9c79a-3e28-4322-b053-5bc5bacb0b9c" width="300" />| <img src="https://github.com/user-attachments/assets/52cd10be-e975-482c-a0bd-c04e936159b7" width="300" /> | <img src="https://github.com/user-attachments/assets/9c039f4b-2a39-4f85-8a4c-1fbcd58e0a07" width="300" /> |<img src="https://github.com/user-attachments/assets/5119a2b7-8b89-47b7-aa2c-b335fecb75c9" width="300" />|
- 他に方法がありましたらコメントをいただけると幸いです
=> About画面の各アイコンのエフェクトが反映される領域の調整

.github/workflows/deploy-app-ios.yaml, .vscode/cspell.json, apps/app/.gitignore, apps/app/ios/Runner/ExportOptions.plist, apps/app/ios/fastlane/Fastfile, melos.yaml
#439 
App Store へデプロイ用のワークフローを仮作成しました。
処理とかも一旦適当に作成しています。
リリースブランチでデプロイの検証するため、ぱっと見おかしなことしていそうにないか確認して Approve いただければと思います 🙏 
特になし
- https://developer.apple.com/help/account/create-certificates/cloud-managed-certificates/
- https://zenn.dev/welchi/articles/flutter-ios-ci-cd-xcode-cloud
- https://zenn.dev/yorifuji/articles/build-automatically-manage-singin-on-ci
- https://qiita.com/arasan01/items/7521255be581ac451c4f
- https://cam-inc.co.jp/p/techblog/956439539012861954
- https://melos.invertase.dev/environment-variables
=> [App] ci: App Store へデプロイ用のワークフローを仮作成

.vscode/settings.json, apis/ticket-api/package.json, apis/ticket-api/src/routes/v1/payment.ts, apis/ticket-api/src/routes/v1/v1.ts, apis/ticket-api/src/routes/v1/wallet.ts, packages/common/ticket_api/lib/model/payment/payment_refund_response.dart, packages/common/ticket_api/lib/model/payment/payment_refund_response.freezed.dart, packages/common/ticket_api/lib/model/payment/payment_refund_response.g.dart, packages/common/ticket_api/lib/model/payment/payment_search_response.dart, packages/common/ticket_api/lib/model/payment/payment_search_response.freezed.dart, packages/common/ticket_api/lib/model/payment/payment_search_response.g.dart, packages/common/ticket_api/lib/ticket_api.dart, packages/common/ticket_api/lib/ticket_api.g.dart, pnpm-lock.yaml
- 返金APIを実装しました  
すべての返金関連APIは`role() = admin` のみ実行可能です
- `v1/payment/search` Emailから支払いIDを検索するAPI
- `v1/payment/refund` 支払いIDの支払いを返金するAPI
- 返金に成功・失敗した時にSlack Incoming webhook経由で通知が行きます
=> [ticket-api] 返金APIを実装

packages/common/data/supabase/migrations/20241120145542_alter_section_rls.sql
- 区画IDを保管する`public.sections`テーブルに対するRLSが有効になっていなかった
- 任意のユーザがSELECTしても問題のないテーブルではある
- UPDATE/DELETE/CREATE されておらず、意図したデータが保持されていることは確認しました
- production/staging環境にmigration済みです
=> fix(data): sectionsテーブルに対するRLSを有効化

apis/ticket-api/wrangler.toml
=> chore(ticket-api): チケット販売状況のSlack Notifyを行うCron Triggerを削除

apps/app/ios/Podfile.lock, packages/app/cores/settings/lib/src/ui/settings_page.dart
- Closes #521 
小さな画面でフォント設定の選択ダイアログにて Bottom Overflow が発生する不具合を修正しました。
[公式ドキュメント](https://api.flutter.dev/flutter/material/AlertDialog-class.html#:~:text=Alert%20dialogs%20and%20scrolling) にある通り、[SingleChildScrollView](https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html) と [ListBody](https://api.flutter.dev/flutter/widgets/ListBody-class.html) を使って対応しました。
| Before | After |
|-|-|
| <img src="https://github.com/user-attachments/assets/04d12637-fa49-4476-bdea-9f9917b6b2e3" width="300" /> | <video src="https://github.com/user-attachments/assets/3d646dc8-c2b7-431c-9b6c-3151411c1831" width=320 /> |
=> [App] fix: 小さな画面でフォント設定の選択ダイアログにて Bottom Overflow が発生する不具合を修正

.github/workflows/replace-contributors.yaml
- Closes #565 
頻繁なコントリビューターの更新処理が不要になったため、↓のファイルの schedule の部分を削除しました。
replace-contributors.yaml
リポジトリのアーカイブでもワークフローの実行を抑制できると思いますが、もう少し開発続くと思ったのでいったんこのように対応することにしました。
見た目の変更がないため省略します。
=> [Data] chore: コントリビューターを更新するワークフローのスケジュール設定を削除
