- apps/website/web/index.html
> [Website] HTMLのtitleとdescriptionを設定

- apps/website/lib/main.dart
- apps/website/web/index.html
-  MaterialAppの引数`title`へ任意の文字列を指定することで ブラウザのタブに文字列を表示できます
> [Website] Titleタグを設定

- apps/website/lib/i18n/strings.g.dart
- apps/website/lib/i18n/strings.i18n.json
- apps/website/lib/ui/components/footer/site_footer.dart
- apps/website/pubspec.lock
- apps/website/pubspec.yaml
- Closes #104
ページフッターに行動規範・プライバシーポリシーなどを追加した。
折り返しアリの場合若干デザインと変わってしまっているが、折り返しのロジックの制約上完全に追従するのが少し難しいため、問題なければこれでいきたいです。
> [webpage]サイトフッターの必須表記追加

- apps/website/web/index.html
> [Website] Google Analytics 4の設定

- apps/website/lib/ui/home/home_page.dart
> 【Web】SelectionAreaを用いてTextを選択できるように

- packages/app/cores/designsystem/pubspec.yaml
- packages/app/features/news/lib/src/ui/news_page.dart
- packages/common/data/pubspec.yaml
- `Pubspec Assist` Extensionを用いて、`pubspec.yaml`内の順番をソートしました
- Dartコード内も合わせて修正しました
> fix(chore): sort imports alphabetically

- packages/common/data/build.yaml
- packages/common/data/lib/src/model/sponsor.dart
- packages/common/data/lib/src/model/sponsor.freezed.dart
- packages/common/data/lib/src/model/sponsor.g.dart
- packages/common/data/lib/src/repository/sponsor_repository.dart
- packages/common/data/lib/src/repository/sponsor_repository.freezed.dart
- packages/common/data/lib/src/repository/sponsor_repository.g.dart
- packages/common/data/lib/src/repository/staff_repository.g.dart
- packages/common/data/lib/src/supabase_client.dart
- packages/common/data/lib/src/supabase_client.g.dart
- packages/common/data/test/connection_test/sponsor_repository_test.dart
- Closes #91
- Sponsor周りのDart Clientを作成しました
- `build.yaml`を作成し、`json_serializable`でデフォルトでスネークケースに変換するようにしました
> [DATA] SponsorのDart Clientを作成

- packages/common/data/docs/procedures_for_updating_staff_related_data.md
- Closes #88 
スタッフ関連データの更新手順を作成しました。
更新することはほとんど発生しないはずなので、自動化は用意していませんが、他のデータの自動化のついでに自動化するかもしれません。
見た目の変更はないため省略します。
> docs: スタッフ関連データの更新手順を作成

- apps/app/pubspec.lock
- packages/app/features/about/lib/src/ui/sponsors/sponsors_item.dart
- packages/app/features/about/lib/src/ui/sponsors/sponsors_page.dart
- packages/app/features/about/pubspec.lock
- packages/app/features/about/pubspec.yaml
なし
↓ のレビューのプルリクエストです。確認して問題なければ Approve 後、マージしていただければ 🙏 
https://github.com/FlutterKaigi/2024/pull/181
> 【App】スポンサー一覧画面のレビュー

- .vscode/cspell.json
- apps/app/lib/routing/router.g.dart
- apps/app/pubspec.lock
- packages/app/cores/designsystem/lib/src/font_family.g.dart
- packages/app/cores/designsystem/lib/src/theme.g.dart
- packages/app/cores/designsystem/pubspec.lock
- packages/app/cores/settings/pubspec.lock
- packages/app/features/about/pubspec.lock
- packages/common/data/lib/src/model/news.g.dart
- packages/common/data/lib/src/repository/news_repository.g.dart
- packages/common/data/lib/src/repository/news_repository_impl.g.dart
なし
警告が出ていたため `cspell.json` を更新したり、 `melos run rebuild` を実行したりしました。
一部の警告は ↓ で対応したため、このプルリクエストでは対応していません。
https://github.com/FlutterKaigi/2024/pull/187
見た目の変更はないため省略します。
> fix: 警告を修正してリビルド

- .vscode/cspell.json
- docs/GET_STARTED.md
- #115
ドキュメントで少し足りない部分や誤解を招いてしまう表現の箇所があったため修正しました。
アプリの見た目の変更はないため省略します。
- できる限り、やさしい日本語で記載するようにしているため、少し違和感のある表現になっているかもしれません。
> docs: GET_STARTED.md を改善

- packages/app/features/about/lib/src/ui/staff/notifer/staff_notifer.dart
- packages/app/features/about/lib/src/ui/staff/staff_card_widget.dart
- packages/app/features/about/lib/src/ui/staff/staff_page.dart
- packages/app/features/about/pubspec.lock
- packages/app/features/about/pubspec.yaml
- packages/app/features/news/pubspec.lock
-  https://github.com/FlutterKaigi/2024/issues/122
スタッフDBの情報をスタッフページに組み込みました
https://github.com/user-attachments/assets/29f7e9f2-ebff-4fa2-b697-648e01ac82a9
> 【App】スタッフページにDBデータを組み込みました

- packages/app/features/about/lib/src/ui/about_page.dart
- Closes #165 
- 会場をタップしたとき、Google Map アプリ へ遷移する機能を作成しました。
- iOS/Android それぞれの動画を添付しました。
- iOS は、Google Map アプリが無い場合のパターン。
- Android は、 Google Map アプリがインストールされているパターン。
| 日本語 | 英語 | Design |
|-|-|-|
| <video src="https://github.com/user-attachments/assets/3d4c5697-7c70-4576-8539-948df4261dc8" width="300" />  | <video src="https://github.com/user-attachments/assets/84de4a3e-583c-404f-ba8e-fd40340901d3" width="300" /> | <img src="https://github.com/user-attachments/assets/b4ad5ad8-f89d-452a-a4e6-438e7cd862d4" width="300" /> | 
| <video src="https://github.com/user-attachments/assets/b0656c17-fadd-40a0-a794-95f43e176c97" width="300" />  | <video src="https://github.com/user-attachments/assets/af2e7763-8dee-451d-8826-26dc0203b2a7" width="300" /> | <img …
> 【App】Google マップ アプリを開く

- apps/website/lib/ui/home/notifier/news_data_notifier.dart
- `analysis_options.yaml`を設定したことで、一部コードで怒られていた
- 修正しました
> [Website] chore: NewsDataNotifierにフォーマッターを適用

- packages/common/data/lib/auth.dart
- packages/common/data/lib/src/model/auth/auth_change_event.dart
- packages/common/data/lib/src/model/auth/user.dart
- packages/common/data/lib/src/model/auth/user.freezed.dart
- packages/common/data/lib/src/model/auth/user.g.dart
- packages/common/data/lib/src/repository/auth_repository.dart
> [data] 認証周りのRepositoryを作成

- .vscode/cspell.json
- apps/ticket_web/pubspec.yaml
- packages/app/features/session/lib/src/ui/session_item.dart
- packages/app/features/session/lib/src/ui/sessions_page.dart
- packages/app/features/session/pubspec.lock
- packages/app/features/session/pubspec.yaml
- https://github.com/FlutterKaigi/2024/issues/20
セッションのタイムラインのWidgetを作成しました。
日付が別々のケース
日付が同じケース
Figmaを参考にしました
https://www.figma.com/design/Uv4GhHJoibnjrxdbnbHzMw/FlutterKaigi-2024-Web-%2B-App?node-id=1063-3942&node-type=frame&t=tZpwCjTpfzMs77qZ-0
> セッションのタイムラインのUI

- apps/ticket_web/lib/pages/home/home_page.dart
> fix: 構文ミスを修正

- packages/app/features/about/lib/src/ui/sponsors/sponsors_page.dart
> [app] (chore) 80文字の文字数制限警告を無視

- packages/common/data/lib/src/model/ticket.dart
- packages/common/data/lib/src/model/ticket.freezed.dart
- packages/common/data/lib/src/model/ticket.g.dart
- packages/common/data/lib/src/repository/ticket_repository.dart
- packages/common/data/lib/src/repository/ticket_repository.g.dart
- packages/common/data/lib/ticket.dart
> [!WARNING]
> - 以下PRをマージしてから本PRをマージしてください
>   - #235 
>   - #237 
>   - #240
>   - #241
>   - #242 
>   - #243 
>   - #245
>   - #246 
>   - #247 
>   - #250 
>   - #252 
>   - #253 
> - PRの宛先を`main`ブランチに変更すること 
- タイトルの通りです
- `TicketRepository().fetchTicketByUserId("[userId]");` でユーザに対するチケットを取得できます
- ない場合は、nullが帰ってきます
> [data, ticket] Ticket Repositoryを作成

- packages/common/data/lib/src/repository/ticket_repository.g.dart
- packages/common/data/lib/ticket.dart
- packages/common/ticket_api/.gitignore
- packages/common/ticket_api/README.md
- packages/common/ticket_api/analysis_options.yaml
- packages/common/ticket_api/build.yaml
- packages/common/ticket_api/lib/model/verify_purchase_response.dart
- packages/common/ticket_api/lib/model/verify_purchase_response.freezed.dart
- packages/common/ticket_api/lib/model/verify_purchase_response.g.dart
- packages/common/ticket_api/lib/src/ticket_api_base.dart
- packages/common/ticket_api/lib/ticket_api.dart
- packages/common/ticket_api/lib/ticket_api.g.dart
- packages/common/ticket_api/pubspec.yaml
> [!WARNING]
> - 以下PRをマージしてから本PRをマージしてください
>   - #235 
>   - #237 
>   - #240
>   - #241
>   - #242 
>   - #243 
>   - #245
>   - #246 
>   - #247 
>   - #250 
>   - #252 
>   - #253 
>   - #255
> - PRの宛先を`main`ブランチに変更すること 
- `common/ticket_api`にTicket API Packageを作成しました
- `/v1/verify_purchase`の返り値を変更します
> [data, ticket] チケットAPIのクライアントを作成

- api/package.json
- api/pnpm-lock.yaml
- api/src/bindings.d.ts
- api/src/index.ts
- api/src/middleware/rateLimiter.ts
- api/src/routes/v1/v1.ts
- api/wrangler.toml
> [ticket] (api) プロモーションコード周りのAPIを作成

- packages/common/ticket_api/build.yaml
- packages/common/ticket_api/lib/model/ticket/get_promotion_response.dart
- packages/common/ticket_api/lib/model/ticket/get_promotion_response.freezed.dart
- packages/common/ticket_api/lib/model/ticket/get_promotion_response.g.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_request.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_request.freezed.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_request.g.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_response.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_response.freezed.dart
- packages/common/ticket_api/lib/model/ticket/post_promotion_response.g.dart
- packages/common/ticket_api/lib/model/ticket/promotion_metadata.dart
- packages/common/ticket_api/lib/model/ticket/promotion_metadata.freezed.dart
- packages/common/ticket_api/lib/model/ticket/promotion_metadata.g.dart
- packages/common/ticket_api/lib/model/verify_purchase_response.g.dart
- packages/common/ticket_api/lib/ticket_api.dart
- packages/common/ticket_api/lib/ticket_api.g.dart
- packages/common/ticket_api/pubspec.yaml
- タイトルの通りです
- #261 で新規作成したAPIに対するクライアントを作成しました
- ついでに、`TicketApi class`のProviderを作成しました
> [ticket] チケットAPI(promotion周り)のClientを作成しました

- apps/app/.gitignore
- apps/app/ios/Podfile.lock
- apps/app/lib/main.dart
- apps/app/lib/routing/router.dart
- apps/app/lib/routing/router.g.dart
- apps/app/lib/routing/routes/main/sessions/sessions_shell_branch.dart
- packages/app/features/news/lib/src/gen/l10n/l10n_en.dart
- packages/app/features/session/assets/l10n/app_en.arb
- packages/app/features/session/assets/l10n/app_ja.arb
- packages/app/features/session/lib/routing.dart
- packages/app/features/session/lib/src/gen/l10n/l10n.dart
- packages/app/features/session/lib/src/gen/l10n/l10n_en.dart
- packages/app/features/session/lib/src/gen/l10n/l10n_ja.dart
- packages/app/features/session/lib/src/providers/bookmarked_sessions.g.dart
- packages/app/features/session/lib/src/routing/router.dart
- packages/app/features/session/lib/src/routing/router.g.dart
- packages/app/features/session/lib/src/ui/bookmarked_sessions_page.dart
- packages/app/features/session/lib/src/ui/session_item.dart
- packages/app/features/session/lib/src/ui/sessions_page.dart
- packages/app/features/session/lib/ui.dart
- packages/app/features/session/pubspec.lock
- packages/app/features/session/pubspec.yaml
- Closes #27
- お気に入りに登録したセッションの一覧画面の実装
- session package のルーティング周りの整備
|-|-|-|
| | | |
> [App] お気に入りセッション一覧画面の実装

- apps/app/pubspec.lock
- apps/ticket_web/pubspec.lock
- apps/ticket_web/pubspec.yaml
- apps/website/pubspec.lock
- apps/website/pubspec.yaml
- packages/app/cores/core/pubspec.lock
- packages/app/cores/designsystem/pubspec.lock
- packages/app/cores/settings/pubspec.lock
- packages/app/features/about/pubspec.lock
- packages/app/features/debug/pubspec.lock
- packages/app/features/news/pubspec.lock
- packages/app/features/session/pubspec.lock
- packages/common/data/pubspec.lock
- packages/common/data/pubspec.yaml
> [all] 依存関係のアップデート

- packages/common/data/supabase/migrations/20241001085856_replace_views_for_null.sql
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/c29a37e0-e4d9-4e11-ae48-bc0064005848)|![image](https://github.com/user-attachments/assets/231486db-1ae3-4b68-b5b9-b95c8609494e)|
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/d9642615-6598-4e89-a906-889d75675895)<br />(セッションが無い場合、結果は返されない状態でした)|![image](https://github.com/user-attachments/assets/02d23676-8abd-4152-a1f4-521013ff0751)|
> [data] Postgres VIEWのリファクタリング

- packages/common/data/supabase/migrations/20241003170401_replace_views_for_null.sql
> [!NOTE]
> - #296 
> をマージしてください
- #305 の問題を修正したバージョンの #296 です
> [ticket] (db) #296([data] Postgres VIEWのリファクタリング) の再作成

- apps/ticket_web/lib/app.dart
- apps/ticket_web/lib/feature/profile/ui/app_bar_avatar.dart
- apps/ticket_web/lib/feature/ticket/ui/components/profile_avatar.dart
- apps/ticket_web/lib/feature/ticket/ui/components/profile_avatar_choice_dialog.dart
- apps/ticket_web/lib/pages/home/home_page.dart
- apps/ticket_web/lib/pages/ticket/ticket_page.dart
> [!NOTE]
> - #307 
> - #303
> をマージしてください
|ログイン時|未ログイン時(アイコンクリックでGoogleログイン遷移)|
|-|-|
|![image](https://github.com/user-attachments/assets/c685dccc-233f-44d2-bdeb-e021908a7186)|![image](https://github.com/user-attachments/assets/7e827734-b29a-4912-ab2e-d22b3ac24435)|
- ログイン状況下における アイコンクリック時
> [ticket] AppBarへログイン状況を移動

- packages/app/features/news/assets/l10n/app_ja.arb
- packages/app/features/news/lib/src/gen/l10n/l10n.dart
- packages/app/features/news/lib/src/gen/l10n/l10n_ja.dart
- Closes #143 
- News関連の多言語対応（初期リリース分）を行いました。
| 日本語 | 英語 | Design |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/9017bc47-8a4c-4e30-80dd-5de4bfaa7468" width="300" />  | <img src="https://github.com/user-attachments/assets/4e8870d6-e6c2-4d75-9024-3cae5c3a24bf" width="300" /> | <img src="https://github.com/user-attachments/assets/9e21f425-30e4-4c94-bb56-1064ac210b57" width="300" /> |  
- 特になし
> [App] News関連の多言語対応（初期リリース分）

- apps/ticket_web/lib/core/provider/image_picker_provider.dart
- apps/ticket_web/lib/feature/ticket/ui/components/ticket_is_adult_card.dart
なし
`melos analyze` で警告が出ていたため修正
特になし
> [ticket] fix: 警告対応

- apps/ticket_web/lib/pages/ticket/components/about_profile_information_card.dart
- packages/common/data/supabase/migrations/20241003170401_replace_views_for_null.sql
> [ticket]  NULLの場合に、成人選択ダイアログを表示

- api/src/util/supabaseSchema.ts
> regenerate supabase types

- apps/ticket_web/lib/feature/profile/data/profile_notifier.dart
- apps/ticket_web/lib/pages/ticket/components/warning_for_personal_sponsor_card.dart
- packages/common/data/lib/src/model/profile.dart
- packages/common/data/lib/src/model/profile.freezed.dart
- packages/common/data/lib/src/model/profile.g.dart
- packages/common/data/lib/src/model/view/profile_with_sns.dart
- packages/common/data/lib/src/model/view/profile_with_sns.freezed.dart
- packages/common/data/lib/src/model/view/profile_with_sns.g.dart
- packages/common/data/lib/src/repository/profile_repository.dart
- packages/common/data/supabase/migrations/20241006202025_alter_profile_is_published.sql
> [ticket] 個人スポンサーの公開設定

- apps/website/lib/feature/news/data/news_data_state.dart
- apps/website/lib/feature/news/ui/news_component.dart
- packages/common/data/lib/src/repository/news_repository_impl.dart
- packages/common/data/lib/src/repository/news_repository_impl.freezed.dart
- packages/common/data/lib/src/repository/news_repository_impl.g.dart
- data: `NewsTable`の型定義が間違えており Newsを正常に取得できていなかったので修正
- website: NewsコンポーネントのUIを微調整しました
> [data, website]: ニュース周りの微調整 (型定義修正・UI調整)

- apps/app/android/app/build.gradle
- apps/app/android/gradle.properties
- apps/app/android/gradle/wrapper/gradle-wrapper.properties
- apps/app/android/settings.gradle
> [App] Upgrade AGP to 8.1.2

- apps/website/web/404.html
> add: 404.htmlを追加し Pathを指定した時の挙動を修正

- apps/website/web/index.html
index.html に記述する必要のあるJavaScriptが抜けていたので 追加しました
> add: 404.htmlを追加し Pathを指定した時の挙動を修正 (index.htmlの対応)

- .github/ISSUE_TEMPLATE/task_for_app_staff.yaml
- .github/ISSUE_TEMPLATE/task_for_data_staff.yaml
- .github/ISSUE_TEMPLATE/task_for_ticket_staff.yaml
- .github/ISSUE_TEMPLATE/task_for_website_staff.yaml
- .github/dependabot.yaml
- .github/labeler.yaml
- .github/workflows/wc-check-sql-format.yaml
なし
外部コントリビュータを受け入れるための準備としてラベルを整理しました。
まだ、 `dependabot/javascript` や `dependencies` など、どうすればいいか分からないものはありますが、いったん、ここまででマージしたいです。
> ci: ラベルを整理

- .github/workflows/labeler-issue.yaml
なし
CI でエラーになっていたため修正しました。
https://github.com/FlutterKaigi/2024/actions/runs/11424520849/job/31784931102#step:4:13
なし
> fix: advanced-issue-labeler の設定ファイルの指定方法ミスを修正

- packages/app/features/about/analysis_options.yaml
- packages/app/features/about/lib/src/data/contributors_provider.dart
- packages/app/features/about/lib/src/data/contributors_provider.g.dart
- packages/app/features/about/lib/src/ui/staff/contributors_page.dart
- packages/app/features/about/pubspec.lock
- packages/app/features/about/pubspec.yaml
- packages/common/data/lib/contributor.dart
- packages/common/data/lib/src/model/contributor.dart
- packages/common/data/lib/src/model/contributor.freezed.dart
- packages/common/data/lib/src/model/contributor.g.dart
- packages/common/data/lib/src/repository/contributor_repository.dart
- packages/common/data/lib/src/repository/contributor_repository.g.dart
- Closes #367 
**※ #366 をマージ後にマージします。**
コントリビューター一覧を Supabase から取得したデータと差し替えました。
ディレクトリ構成の整備や StaffCardWidget を使っている問題などなど、別で対応進めていこうと思います！
※ ローカルで Supabase を起動して仮のデータを入れて表示しています。
https://github.com/user-attachments/assets/5fae0191-6703-46b3-8e33-52129c96a752
> [App] feat: コントリビューター一覧のデータ繋ぎ込み

- .cursorignore
なし
流行り？の [Cursor](https://www.cursor.com/) を利用する際に性能を向上させるために `.cursorignore` を作成しました。
`.cursorrules` はどうするのが適切か微妙で、なお今回はアプリごとに構成が異なるので一旦追加していません。
特になし
- https://docs.cursor.com/context/ignore-files
> [All] chore: cursorignore ファイルを作成

- .github/CODEOWNERS
なし
CODEOWNERS で packages 配下の設定が抜けていたため追加しました。
特になし
> [All] chore: CODEOWNERS で packages 配下の設定追加

- apps/app/lib/main.dart
- packages/app/cores/settings/lib/src/ui/settings_page.dart
- Closes #394
- 言語設定の反映
- 現在の設定値を設定画面のタイルに反映するように
|-|-|-|
| <img src="https://github.com/user-attachments/assets/d3e33d78-2675-49cc-aa0d-a4e220e1987b" width="300" /> | <img src="https://github.com/user-attachments/assets/0ebba66a-8b82-4463-af07-f6c5cf847cb9" width="300" /> | |
> [App]: 言語設定を反映&設定値をすべて設定画面に表示する

- .github/workflows/deploy-ticket.yaml
> fix: PR作成時にStaging-Ticket APIのデプロイを行わないように修正

- packages/common/data/supabase/seed.sql
なし
タイトルの通り。
アカウントが間違えていたようなので、急遽本番DBから手動削除しました。
すでに削除しているため分かりやすいように seed.sql を直接変更しました。
> [Data] fix: minn さんの medium を削除

- .github/workflows/deploy-app-android.yaml
- Closes #413 
タイトルの通り。
ビルド番号のインクリメントは少し面倒なので対応しない方針です。
特になし
> [App] cd: Android アプリを内部テストへアップするワークフロー実装

- apps/app/pubspec.yaml
- Closes #434 
タイトル通り
見た目の変更ないので省略。
> chore: バージョンとバージョンコード更新

- apps/ticket_web/lib/gen/i18n/strings.g.dart
- タイトルの通りです
- `melos rebuild`を実行しました
> fix: 一部自動生成コードが最新になっていない問題を修正

- apps/website/lib/feature/session/data/model/special_session.g.dart
- apps/website/lib/feature/session/data/special_sessions_notifier.dart
- apps/website/lib/feature/session/data/special_sessions_notifier.g.dart
- apps/website/lib/feature/session/ui/components/session_table_card/session_card_content.dart
- apps/website/lib/feature/session/ui/components/session_table_header.dart
- apps/website/lib/ui/components/sponsor_logo.dart
- apps/website/lib/ui/pages/session/components/session_details_card.dart
> [website] タイムテーブルのUIを修正

- .vscode/cspell.json
- docs/GET_STARTED.md
なし
- CocoaPods の記載が漏れていたため追記しました。
- 後々、Swift Package Manager を導入した際に、CocoaPods を使用しなくなったら削除する予定です。
- https://docs.flutter.dev/packages-and-plugins/swift-package-manager/for-app-developers
- IDEA の動作保証バージョンや Android Studio についての補足事項を追記しました。
特にアプリの挙動の変更はないため省略します。
> [All] docs: GET_STARTED の内容で記載漏れていた内容を追記

- packages/app/features/about/assets/l10n/app_en.arb
- packages/app/features/about/assets/l10n/app_ja.arb
- packages/app/features/about/lib/src/gen/l10n/l10n.dart
- packages/app/features/about/lib/src/gen/l10n/l10n_en.dart
- packages/app/features/about/lib/src/gen/l10n/l10n_ja.dart
- packages/app/features/about/lib/src/ui/about_page.dart
- packages/app/features/about/lib/src/ui/contributors/contributors_list_item.dart
- Closes #398 
- issueに添付の枠線ありのデザインに変更
- contribute数が画面に収まり切る場合は、非活性表示と活性表示を出し分けている
- contribute数が画面に収まりきらない場合は、末尾に「+xx」という表記で表示する様にしている
- 画面解像度によってはTextの比率が変更されてしまうため、一マスに文字列数を最大2文字として定義し、文字列数に応じてTextを表示するマスを増やしています。
| | |
|-|-|
|iPhone16Pro light | iPhone16Pro dark |
| <img src="https://github.com/user-attachments/assets/0b3f375f-9e27-4945-9804-d037edb8e665" width="300" />|<img src="https://github.com/user-attachments/assets/a33e196b-c558-4322-8830-a4d59fe1acae" width="300" /> |
| | |
|-|-|
|iPhoneSE 3rd light | iPhoneSE 3rd dark |
|<img src="https://github.com/user-attachments/assets/763a8ea3-a298-40ec-bc9b-28bd58631694" width="300" /> |<img src="https://github.com/user-attachments/assets/251ef5f8-dc0b-4029-af05-4657573d725a" width="300" /> |
| | |
|-|-|
|iPad Air 13 inch light | iPad …
> #398 コントリビューター一覧に草を生やす

- apis/website-html-rewriter/package.json
- apis/website-html-rewriter/src/bindings.d.ts
- apis/website-html-rewriter/src/ogImage.tsx
- apis/website-html-rewriter/src/server.ts
- apis/website-html-rewriter/src/util/ogpRewriter.ts
- biome.json
- トップレベルで`pnpm check`, `pnpm lint`等のコマンドを実行した時に`website-html-rewriter`がチェックされていなかった
- `website-html-rewriter`パッケージの`packages.json -> scripts`に`lint` `check` `format`の記載がなかったため。
- 追加しました
- Biomeに怒られていた部分の修正を行いました
- 実装の変更はありません
> [website-api] Linter・Formatter周りの強化・修正

- packages/app/features/session/lib/src/ui/session_page.dart
- Closes #23
- セッションのタイトルとURLをXで共有する機能を追加
|-|-|-|
| | | |
> [App]: セッションを SNS で共有する機能を追加

- packages/app/features/session/lib/src/data/model/timeline_item.dart
- packages/app/features/session/lib/src/data/model/timeline_item.freezed.dart
- packages/app/features/session/lib/src/data/providers/session_timeline.dart
- packages/app/features/session/lib/src/data/providers/session_timeline.g.dart
- packages/app/features/session/lib/src/ui/timeline_item_view.dart
- Closes #437
- セッション一覧にセッション情報以外の情報を表示するように
|-|-|-|
| | | |
> [App]: セッション以外のタイムテーブルイベントを追加

- .github/workflows/deploy-supabase.yaml
なし
replace-contributors を replace_contributors と typo していたため修正しました。
↓無事に成功しました 🎉 
https://github.com/FlutterKaigi/2024/actions/runs/11766549704/job/32774208949
> fix: typo を修正（replace-contributors）

- packages/common/data/supabase/migrations/20241111131632_alter_app_minimum_versions_policy.sql
- packages/common/data/supabase/migrations/20241111131940_alter_realtime_publication.sql
- packages/common/data/supabase/tests/app_minimum_versions_test.sql
#459 
- Realtime 機能は anonymous user（匿名ユーザー）に絞る必要があるため修正しました。
- supabase_realtime という publication を作成して、購読対象のテーブルを追加する必要があったため、マイグレーションファイルを作成しました。
見た目に関する変更はありません。
全てテスト通過したこと確認済です。
- https://supabase.com/docs/guides/realtime/subscribing-to-database-changes
- https://supabase.com/docs/guides/database/postgres/row-level-security
- https://supabase.com/docs/guides/realtime/postgres-changes?queryGroups=database-method&database-method=sql&queryGroups=language&language=dart
> [Data] feat: Supabase Realtime の設定

- .github/workflows/deploy-app-android.yaml
- apps/app/android/fastlane/Fastfile
- apps/app/ios/InfoPlist.xcstrings
- apps/app/ios/Runner.xcodeproj/project.pbxproj
- apps/app/ios/Runner/Info.plist
- apps/app/ios/Runner/Runner.entitlements
- apps/app/ios/en.lproj/InfoPlist.strings
- apps/app/ios/ja.lproj/InfoPlist.strings
- apps/app/pubspec.yaml
なし
リリースに必要な作業を行い、審査に提出して無事に通っていつでもリリースできる状態となりました。
- アプリバージョンとビルドナンバーを更新しました
- Native Debug Symbol や Mapping ファイルをアップロードするように設定しました
- PUSH 通知は利用していないが、使用している何かしらのプラグインが ITMS-90078 というレビュー事項に引っかかってしまったので、えいやで Capavility で「Push Notifications」を追加しました
- アーカイブを作成するタイミングだと Info.plist の変数の中身が空になってしまって ITMS-90683 というレビュー事項に引っかかってしまっていたので、Info.plist の多言語対応を String Catalog を使う方法に移行して、Info.plist には英語の文言を入れておくようにしました。（もっと適切な方法があれば教えていただけると助かります 🙏 ）
Google Play Store / App Store 両方で審査通って、いつでもリリースできる状態になりました。
> [App] release: 0.3.0+7

- .github/workflows/deploy-website.yaml
https://flutterkaigi.slack.com/archives/C06MYMA88AX/p1731519385229879
> [website] (fix-ci): コミットメッセージに空白が入っていた場合 Websiteデプロイでエラーが起きる問題を修正

- packages/common/data/supabase/seed.sql
なし
DM で修正依頼受けまして、すでに本番反映済みです。
反映されていること確認済みです。
> fix: 表示名を akeybako に変更

- packages/app/features/about/lib/src/ui/sponsors/sponsors_list_item.dart
- Closes #389 
`SponsorsListItem._SponsorImage`クラスにSemanticsクラス追加
|-|-|-|
| <img src="https://github.com/user-attachments/assets/36cc33a4-d940-434f-9785-ff6b35c865f2" width="300" /> | <img src="https://github.com/user-attachments/assets/d385843a-fa2c-47ba-994a-2fa51b1071a4" width="300" /> | |
> [App] スポンサー画像にSemantics設定追加

- apps/ticket_reader/lib/features/profile/ui/entry_log/entry_log_detail.dart
- apps/ticket_reader/lib/features/profile/ui/entry_log/entry_log_view.dart
- apps/ticket_reader/lib/features/profile/ui/entry_log/no_entry_log_card.dart
- apps/ticket_reader/lib/features/profile/ui/entry_log_view.dart
- apps/ticket_reader/lib/features/profile/ui/ticket_qr_dialog.dart
- apps/ticket_reader/lib/features/profile/ui/user_card.dart
- apps/ticket_reader/lib/pages/home_page.dart
- apps/ticket_reader/lib/pages/ticket_reader_page.dart
- apps/ticket_reader/pubspec.yaml
- packages/common/data/supabase/migrations/20241117163548_add_entry_log.sql
- Build 2としてTestFlightにアップロード済み
- QR読み取り -> UserCardを表示する部分の実装を行いました
> [ticket-reader] QR読み取り機能を実装

- apis/ticket-api/src/routes/v1/payment.ts
- apps/ticket_reader/lib/core/router/router.g.dart
- apps/ticket_reader/lib/features/auth/data/auth_notifier.g.dart
- apps/ticket_reader/lib/features/payment/data/payment_notifier.dart
- apps/ticket_reader/lib/features/payment/data/payment_notifier.g.dart
- apps/ticket_reader/lib/features/payment/data/payment_repository.dart
- apps/ticket_reader/lib/features/payment/ui/payment_card.dart
- apps/ticket_reader/lib/features/profile/ui/entry_log/entry_log_detail.dart
- apps/ticket_reader/lib/features/profile/ui/user_card.dart
- apps/ticket_reader/lib/pages/home_page.dart
- apps/ticket_reader/lib/pages/payment_search_page.dart
- packages/common/ticket_api/lib/model/payment/payment_search_response.dart
- packages/common/ticket_api/lib/model/payment/payment_search_response.freezed.dart
- packages/common/ticket_api/lib/model/payment/payment_search_response.g.dart
- packages/common/ticket_api/lib/ticket_api.dart
- packages/common/ticket_api/lib/ticket_api.g.dart
> [ticket-reader] 返金APIの修正・それに伴うアプリ側修正

- apis/ticket-api/src/routes/v1/payment.ts
- fix: 返金APIのログ出力・・エラーレスポンスの改善
> [ticket-api] 返金APIのログ出力・・エラーレスポンスの改善

- packages/common/data/lib/src/model/view/session_venues_with_sessions_v4_view.dart
- packages/common/data/lib/src/model/view/session_venues_with_sessions_v4_view.freezed.dart
- packages/common/data/lib/src/model/view/session_venues_with_sessions_v4_view.g.dart
- packages/common/data/lib/src/repository/session_repository.dart
- packages/common/data/supabase/migrations/20241221151700_alter_sessions_video_url.sql
- packages/common/data/supabase/migrations/20241222112928_add_session_venues_with_sessions_v4.sql
- packages/common/data/supabase/seed.sql
#456
※ まだアプリ・ウェブサイトへ組み込んでいないためクローズはしません。
セッション動画の URL を DB に追加して、 common_data パッケージを修正して取得できるようにしました。
↓で開発環境で DB リセットしても video_url が反映されるようにしました。
0c82fb9f68c71ffadc64e10ab044963ca6e5725f
<details><summary>本番環境で動画 URLを追加する方法</summary>
<p>
SQL Editor で次の SQL を実行する予定です。（開発環境ではお試し済み）
```sql
WITH
speaker_sessions AS (
SELECT DISTINCT
ss.session_id,
s.name
FROM
speakers s
JOIN session_speakers_v2 ss ON s.id = ss.speaker_id
WHERE
s.name IN (
'Masatoshi Tsushima',
'mori',
'よーたん',
'若宮浩司',
'みね',
'futabooo',
'batch',
'そた',
'KyoheiG3',
'Ren Edakawa',
'Masahiro Aoki',
'新垣清奈',
'としき',
'金ちゃん',
'ぎもちん',
'おさたく',
'ちゅーやん',
'ronnnnn',
'Jeffrey Bunn',
'Dreamwalker',
'Koki Yoshida',
'Aoi Umigishi',
'akaboshinit',
'廣部貴徳',
'後藤 孝輔',
'chigichan24',
'techiro',
'Kosuke Saigusa',
'たまねぎ'
)
)
UPDATE sessions s
SET …
```
> [Data] feat: セッション動画の URL を DB に追加

- packages/common/data/supabase/migrations/20241120234055_add_entry_log_summary_view.sql
なし
タイトルの通りです。
詳しくは↓をご覧ください。
https://flutterkaigi.slack.com/archives/C06T5TXN19R/p1735081305490809
見た目の変更はないため省略します。
> [Data] fix: 本番環境へは反映されていたが追加していなかったマイグレーションファイルを追加

- apps/app/pubspec.yaml
なし
バージョンとバージョンコードを更新しました。
~※ 現在審査中でストアに公開したらオープンにします。~
→ ストアに公開したためオープンにしました。
特に変更ないため省略します。
> [App] Release/app 1.1.0

- packages/common/data/lib/src/repository/contributor_repository.dart
- packages/common/data/lib/src/repository/contributor_repository.g.dart
- packages/common/data/lib/src/repository/job_board_repository.dart
- packages/common/data/lib/src/repository/job_board_repository.g.dart
- packages/common/data/lib/src/repository/news_repository.dart
- packages/common/data/lib/src/repository/news_repository.g.dart
- packages/common/data/lib/src/repository/news_repository_impl.dart
- packages/common/data/lib/src/repository/speaker_repository.dart
- packages/common/data/lib/src/repository/speaker_repository.g.dart
#563 
以下のリポジトリのデータ取得をSupabaseからローカルJSONに変更しました。
- ContributorRepository
- JobBoardRepository
- NewsRepository
- SpeakerRepository
残りは別途作業予定です。
※ SpeakerRepository は未使用のものを削除しただけ
関係箇所
- ContributorRepository
- NewsRepository
https://github.com/user-attachments/assets/a7eab8ec-1c07-4403-8f03-4e54596215e8
関係箇所
- JobBoardRepository
- NewsRepository
https://github.com/user-attachments/assets/3b85c9bd-db99-48fa-b71e-7b5e37b8208d
> [Data] feat: データ取得をローカルJSONに変更

- packages/common/data/lib/src/repository/app_minimum_version_repository.dart
- packages/common/data/lib/src/repository/app_minimum_version_repository.g.dart
#563 
以下のリポジトリのデータ取得をSupabaseからローカルJSONに変更しました。
AppMinimumVersionRepository
残りは別途作業予定です。
起動することのみ確認しました。
> [Data] feat: appMinimumVersions データ取得をローカルJSONに変更

- apps/app/pubspec.yaml
- apps/website/macos/Podfile.lock
なし
バージョンとバージョンコードを更新しました。
※ 現在審査準備中でストアに公開したらオープンにします
特に変更ないため省略します。
> [App] Release/app 2.0.0
